<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TTMLSIE" failures="2" tests="9" name="dsAlgo_Runner.TestRunner" time="11.644" errors="0" timestamp="2025-04-14T21:27:58 EDT" skipped="0">
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.123">
    <failure message="expected [Invalid password] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Invalid password] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Register_SD.the_user_is_not_able_to_see_error_msg_after_entering_invalid_password(Register_SD.java:132)
at ✽.The user is not able to see error msg after entering invalid password(file:///C:/Kalyani/code/DsAlgo_BDD/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD02_Register.feature:44)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.170"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.769"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="2.764"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="3.128"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.985"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.186">
    <failure message="expected [Invalid username] but found [password_mismatch:The two password fields didn’t match.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Invalid username] but found [password_mismatch:The two password fields didn’t match.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:186)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:25)
at org.testng.asserts.Assertion.doAssert(Assertion.java:12)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:182)
at dsAlgo_stepDefinition.Register_SD.the_user_is_not_able_to_see_error_msg_after_entering_invalid_data(Register_SD.java:112)
at ✽.The user is not able to see error msg after entering invalid data(file:///C:/Kalyani/code/DsAlgo_BDD/DsAlgo_ProjectCompass_BDD/src/test/resources/dsAlgo_FeatureFiles/MD02_Register.feature:37)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="1.282"/>
  <testcase classname="dsAlgo_Runner.TestRunner" name="runScenario" time="0.237"/>
</testsuite> <!-- dsAlgo_Runner.TestRunner -->
